apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  labels:
    app: mysql
data:
  root-password: cGhhbmkxMjM=
  root-user: cm9vdA==


 
# Encode base 64
# echo -n phani123|base64
# Decode base 64 
# echo -n cGhhbmkxMjM= |base64 -d
